# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Jobs
  jobs:  
  - job: Build
    displayName: Agent job (ARM)
    timeoutInMinutes: 210
    cancelTimeoutInMinutes: 210
    
    pool:
      name: WorkerPool
      demands: Agent.OSArchitecture -equals ARM

    steps:      
    - template: ap-template-docker-buildimage.yml
      parameters:
        dockerRegistryConnection: 'dockerhub_johanthedeveloper'
        dockerFile: '**/dockerfile'
        repository: 'johanthedeveloper/verium-dev' 
        tagName: '$(Build.BuildNumber)' 

    - template: ap-template-docker-pushimage.yml
      parameters:
        dockerRegistryConnection: 'dockerhub_johanthedeveloper'
        repository: 'johanthedeveloper/verium-dev' 
        tagName: '$(Build.BuildNumber)' 
        
    - template: ap-template-docker-buildimage.yml
      parameters:
        dockerRegistryConnection: 'dockerhub_johanthedeveloper'
        dockerFile: '**/dockerfile'
        repository: 'johanthedeveloper/verium' 
        tagName: '$(Build.BuildNumber)' 

    - template: ap-template-docker-pushimage.yml
      parameters:
        dockerRegistryConnection: 'dockerhub_johanthedeveloper'
        repository: 'johanthedeveloper/verium' 
        tagName: '$(Build.BuildNumber)' 
